### ISSUE TITLE
im.lfo would benefit from a retrigger option

### ISSUE THREAD

**Issue by alexmlucas** [matthewscharles/instrument-maker#21]
It would be useful to be able to reset the phase of im.lfo via a separate inlet.

**Comment by matthewscharles** [comment]
Just added this df7c0c5304c3a952f37405ceaa506f0a1a392c5a 
Let me know if it works the way you expect!

**Comment by matthewscharles** [comment]
(I guess linking to the update is less useful, but you should be able to pull and try that out..it takes a signal in the right-most inlet, also see updated help file)

**Comment by alexmlucas** [comment]
Thanks for implementing this so quickly! it works a treat!
