### ISSUE TITLE
im.envelope has no help file

### ISSUE THREAD

**Issue by alexmlucas** [matthewscharles/instrument-maker#22]
im.envelope has no help file - a description of the arguments would be useful.

**Comment by matthewscharles** [comment]
I hadn't really looked at this properly since I made it for a workshop.  Looks like it's an AHR envelope, I need to clarify this.  I've made a temp help file for now.

**Comment by alexmlucas** [comment]
As it happens, AHR might be more useful for switch applications. Thanks!
