### ISSUE TITLE
im.reverb help file is empty

### ISSUE THREAD

**Issue by alexmlucas** [matthewscharles/instrument-maker#23]
A basic example would be useful.

**Comment by matthewscharles** [comment]
Something there now.  The object itself could use a bit of work.  I originally had freeverb~ in there as a quick fix, and I'm not so familiar with the rev1~ abstraction.  Longer reverb times seem to affect the overall shape. As a basic demo, it should do the trick.

**Comment by alexmlucas** [comment]
Brilliant, thank you!
