### ISSUE TITLE
No audio output from im.acid

### ISSUE THREAD

**Issue by alexmlucas** [matthewscharles/instrument-maker#30]
I cannot get an audible audio signal from im.acid in the following configuration. Am I missing something?

```
[im.keypress q]
|
[im.step 8]
|
[im.sequence 0 1 2 3 4 5 6 7]
|
[im.scale C major 6]
|
[im.acid]
|
[im.speaker]
```

**Comment by matthewscharles** [comment]
The filter input range was way too low -- should work now!

There are a couple more changes needed here (set PWM input to signal rather than message)

**Comment by alexmlucas** [comment]
Thanks Charles. I can see the issue's been fixed on Github, but can't seem to fetch any changes since I changed the im.sequence and im.step help files. I've checked that I'm on the master branch - am I missing something?

**Comment by matthewscharles** [comment]
ah, github..I'm not sure what could be going wrong there. are you running the desktop client? I'm currently updating in a branch called restructure..the acid fix predates that, but it might be worth switching to that branch to see if you can pull temporarily at least.

**Comment by alexmlucas** [comment]
Yes, I'm using the desktop client but switching to the restructure branch fixed it! Thanks!
